import { products, locales } from '../catalog.mjs';
import { url, assetUrl } from '../paths.mjs';
export { url, assetUrl } from '../paths.mjs';
export const e = value => String(value ?? '').replace(/[&<>"']/g, x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
export const br = value => e(value).replace(/\n/g,'<br>');
const paths = {
 arrow:'M4 12h16m-6-6 6 6-6 6',chevron:'m6 9 6 6 6-6',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18Z',
 menu:'M4 6h16M4 12h16M4 18h16',close:'m6 6 12 12M6 18 18 6',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',
 chat:'M21 11a8 8 0 0 1-8 8H6l-4 3V11a9 9 0 0 1 19 0ZM7 10h10M7 14h6',send:'m22 2-7 20-4-9-9-4 20-7ZM11 13 22 2',check:'m5 12 4 4L19 6',
 box:'m3 7 9-4 9 4v10l-9 4-9-4V7Zm0 0 9 4 9-4M12 11v10M7.5 5l9 4v5',file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6Zm0 0v6h6M8 13h8M8 17h5',
 shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Zm-4 9 3 3 5-6',info:'M12 16v-4M12 8h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',
 mail:'M3 5h18v14H3V5Zm0 0 9 8 9-8',plus:'M12 5v14M5 12h14',building:'M4 21V3h12v18M2 21h20M16 9h4v12M8 7h4M8 11h4M8 15h4M9 21v-3h2v3',
 heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z'
};
export const icon = (name,cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.box}"/></svg>`;
export const logo = () => `<span class="brand-symbol" aria-hidden="true"><i></i><i></i><i></i><i></i></span><span class="brand-word" dir="ltr">KS<span class="brand-period">.</span></span>`;
export const button = (text,href,secondary=false) => `<a class="button ${secondary?'button-secondary':''}" href="${e(href)}">${e(text)}${icon('arrow','directional')}</a>`;
export function productCard(p,t,lang,filterable=false) {
 const text=t.products[p.id];
 return `<article class="product-card reveal" ${filterable?`data-product="${p.id}" data-category="${p.category}" data-search="${e([text.name,text.short,t.catalog[p.category],p.id].join(' '))}"`:''}>
 <a href="${url(lang,`products/${p.id}/`)}" class="product-card-link"><div class="product-art art-${p.art}" data-depth="card"><span class="product-ref" dir="ltr">${p.ref}</span><img src="${assetUrl(`images/${p.art}.webp`)}" alt="" width="804" height="612" loading="lazy" decoding="async"><span class="art-open">${icon('arrow','directional')}</span></div>
 <div class="product-card-text"><span class="category-label">${e(t.catalog[p.category])}</span><h3>${e(text.name)}</h3><p>${e(text.short)}</p><span class="text-link">${e(t.common.view)} ${icon('arrow','directional')}</span></div></a></article>`;
}
export function cta(t,lang) {return `<section class="container cta-section reveal"><div class="cta-copy"><span class="eyebrow light">${e(t.common.eyebrow)}</span><h2>${br(t.home.ctaTitle)}</h2><p>${e(t.home.ctaText)}</p>${button(t.home.ctaButton,url(lang,'contact/'))}</div><div class="cta-depth-rings" aria-hidden="true"><i></i><i></i><i></i></div></section>`;}
export function faq(t) {return `<section class="container faq-section reveal"><div><span class="eyebrow">${e(t.nav.contact)}</span><h2>${e(t.faq.title)}</h2></div><div class="faq-list">${t.faq.items.map(x=>`<details><summary>${e(x.q)}${icon('plus')}</summary><p>${e(x.a)}</p></details>`).join('')}</div></section>`;}
export function layout(t,locale,path,body,config={},pageTitle='') {
 const {code:lang,dir,tag}=locale;
 const isHome = path==='';
 const title = pageTitle?`${pageTitle} | ${t.meta.site}`:t.meta.site;
 const active = path.split('/')[0]||'home';
 const navLinks=[['home',''],['products','products/'],['about','about/'],['contact','contact/']];
 const canonical=config.siteUrl?new URL(url(lang,path),config.siteUrl).href:'';
 const data={locale:lang,path,basePath:config.basePath||'',contactEndpoint:config.contactEndpoint||'/api/contact',contactEnabled:config.contactEnabled||false,turnstileSiteKey:config.turnstileSiteKey||'',t:{nav:t.nav,contact:t.contact,chat:t.chat,catalog:t.catalog,common:t.common,imagery:t.imagery},products:products.map(p=>({...p,...t.products[p.id]}))};
 return `<!DOCTYPE html><html lang="${tag}" dir="${dir}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#153f39"><title>${e(title)}</title><meta name="description" content="${e(t.meta.description)}">${config.preview?'<meta name="robots" content="noindex,nofollow">':''}${canonical?`<link rel="canonical" href="${canonical}">${locales.map(l=>`<link rel="alternate" hreflang="${l.tag}" href="${new URL(url(l.code,path),config.siteUrl).href}">`).join('')}<link rel="alternate" hreflang="x-default" href="${new URL(url('en',path),config.siteUrl).href}">`:''}<meta property="og:type" content="website"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(t.meta.description)}"><link rel="icon" type="image/svg+xml" href="${assetUrl('favicon.svg')}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Noto+Sans:wght@400;500;600;700&family=Noto+Sans+Arabic:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="${assetUrl('styles.css')}"><script src="${assetUrl('app.js')}" defer></script></head><body data-page="${e(active)}">
 <a class="skip-link" href="#main">${e(t.nav.skip)}</a>
 <header class="site-header"><div class="container header-inner"><a class="brand" href="${url(lang)}" aria-label="${e(t.meta.site)}">${logo()}</a><nav class="desktop-nav" aria-label="${e(t.nav.menu)}">${navLinks.map(([key,link])=>`<a href="${url(lang,link)}"${active===key?' aria-current="page"':''}>${e(t.nav[key])}</a>`).join('')}</nav><div class="header-actions"><div class="language-control">${icon('globe')}<label class="sr-only" for="language">${e(t.nav.language)}</label><select id="language" data-language-selector>${locales.map(l=>`<option value="${l.code}" lang="${l.tag}" ${lang===l.code?'selected':''}>${e(l.name)}</option>`).join('')}</select>${icon('chevron')}</div><a href="${url(lang,'contact/')}" class="button button-small header-cta">${e(t.nav.enquire)}${icon('arrow','directional')}</a><button class="icon-button menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu" aria-label="${e(t.nav.menu)}">${icon('menu')}</button></div></div><nav class="mobile-nav" id="mobile-menu" aria-label="${e(t.nav.menu)}" hidden>${navLinks.map(([key,link])=>`<a href="${url(lang,link)}"${active===key?' aria-current="page"':''}>${e(t.nav[key])}${icon('arrow','directional')}</a>`).join('')}</nav></header>
 <main id="main" tabindex="-1">${body}</main>
 <footer class="site-footer"><div class="container footer-grid"><div class="footer-brand"><a class="brand" href="${url(lang)}" aria-label="${e(t.meta.site)}">${logo()}</a><p>${e(t.common.footerDesc)}</p><span class="footer-small">${e(t.common.notCheckout)}</span></div><div><h2>${e(t.common.footerProducts)}</h2>${products.map(p=>`<a href="${url(lang,`products/${p.id}/`)}">${e(t.products[p.id].name)}</a>`).join('')}</div><div><h2>${e(t.common.footerCompany)}</h2><a href="${url(lang,'about/')}">${e(t.nav.about)}</a><a href="${url(lang,'contact/')}">${e(t.nav.contact)}</a><a href="${url(lang,'privacy/')}">${e(t.common.privacy)}</a></div><div><h2>${e(t.common.footerLanguages)}</h2>${locales.map(l=>`<a href="${url(l.code,path)}" data-locale-link="${l.code}" lang="${l.tag}" class="footer-language"><bdi>${e(l.name)}</bdi><span dir="auto">${e(l.region)}</span></a>`).join('')}</div></div><div class="container footer-bottom"><span>© ${new Date().getUTCFullYear()} ${e(t.common.rights)}</span><p>${e(t.common.footerNote)}<span class="footer-media-note">${e(t.imagery.disclaimer)}</span></p></div></footer>
 <div class="chat-widget"><button class="chat-launcher" aria-label="${e(t.chat.open)}" aria-expanded="false" aria-controls="chat-panel"><span class="chat-button-label">${e(t.chat.needHelp)}</span>${icon('chat')}</button><section class="chat-panel" id="chat-panel" role="dialog" aria-modal="false" aria-labelledby="chat-title" hidden><div class="chat-header"><span class="chat-avatar" aria-hidden="true">KS</span><div><h2 id="chat-title">${e(t.chat.title)}</h2><p>${e(t.chat.subtitle)}</p></div><button class="icon-button chat-close" aria-label="${e(t.chat.close)}">${icon('close')}</button></div><div class="chat-messages" role="log" aria-live="polite" aria-relevant="additions" aria-label="${e(t.chat.title)}"></div><div class="chat-chips">${t.chat.chips.map((x,i)=>`<button type="button" data-chat-topic="${['products','bulk','documents','contact'][i]}">${e(x)}</button>`).join('')}</div><form class="chat-form"><label class="sr-only" for="chat-input">${e(t.chat.inputLabel)}</label><input id="chat-input" type="text" maxlength="500" autocomplete="off" placeholder="${e(t.chat.placeholder)}" dir="auto"><button class="icon-button" type="submit" aria-label="${e(t.chat.send)}">${icon('send','directional')}</button></form><p class="chat-disclaimer">${e(t.chat.hint)}</p></section></div>
 <script id="site-data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script></body></html>`;
}
