import {products,locales} from '../catalog.mjs';
import {e,br,url,assetUrl,icon,button,productCard,cta,faq,logo} from './components.mjs';
const eyebrow = text => `<span class="eyebrow">${e(text)}</span>`;
const heading = (tag,title,desc) => `<div class="page-heading">${eyebrow(tag)}<h1>${br(title)}</h1>${desc?`<p>${e(desc)}</p>`:''}</div>`;
function brandArt(t) {
 return `<figure class="photography-story" data-depth="story"><div class="story-surface" aria-hidden="true"></div><img class="story-main" src="${assetUrl('images/infusion.webp')}" alt="${e(t.products['iv-infusion-sets'].name)}" width="804" height="612" loading="lazy"><div class="story-inset"><img src="${assetUrl('images/cannula.webp')}" alt="${e(t.products['iv-cannulas'].name)}" width="804" height="612" loading="lazy"><span>${e(t.products['iv-cannulas'].name)}</span></div><figcaption><span class="story-monogram" dir="ltr">KS.</span><span>${e(t.home.aboutNote)}</span></figcaption></figure>`;
}
function heroArt(t,lang) {
 return `<div class="hero-media"><div class="photo-showcase" data-depth="hero"><div class="showcase-cap"><div><span class="eyebrow">${e(t.hero.focus)}</span><strong>${e(t.hero.focusName)}</strong></div><span class="showcase-index" dir="ltr">KS / 01 — 06</span></div><a class="hero-photo-link" href="${url(lang,'products/iv-infusion-sets/')}" aria-label="${e(t.products['iv-infusion-sets'].name)}"><img class="hero-photo" src="${assetUrl('images/hero.webp')}" alt="${e(t.hero.artLabel)}" width="671" height="234" fetchpriority="high"><span class="hero-photo-action" aria-hidden="true">${icon('arrow','directional')}</span></a><div class="showcase-products">${['iv-infusion-sets','iv-cannulas'].map(id=>{const p=products.find(x=>x.id===id);return `<a class="showcase-product" href="${url(lang,`products/${p.id}/`)}"><img src="${assetUrl(`images/${p.art}.webp`)}" width="804" height="612" alt=""><span><small dir="ltr">${p.ref}</small><strong>${e(t.products[id].name)}</strong></span>${icon('arrow','directional')}</a>`;}).join('')}</div></div><p class="hero-media-caption">${e(t.imagery.shortNote)}</p></div>`;
}
export function home(t,lang) {return `<section class="container hero"><div class="hero-copy"><div class="eyebrow pill-eyebrow"><span></span>${e(t.hero.tag)}</div><h1>${e(t.hero.line1)}<br><em>${e(t.hero.line2)}</em></h1><p>${e(t.hero.desc)}</p><div class="button-row">${button(t.hero.cta,url(lang,'products/'))}<a class="quiet-link" href="${url(lang,'contact/')}">${e(t.hero.secondary)}${icon('arrow','directional')}</a></div><div class="audiences"><span>${e(t.hero.audience)}</span><i></i><span>${e(t.hero.audience2)}</span><i></i><span>${e(t.hero.audience3)}</span></div></div>${heroArt(t,lang)}</section>
 <section class="container benefits" aria-label="${e(t.nav.about)}">${t.benefits.map((x,i)=>`<div><span class="benefit-number" aria-hidden="true" dir="ltr">0${i+1}</span><div><h2>${e(x.title)}</h2><p>${e(x.text)}</p></div></div>`).join('')}</section>
 <section class="container section catalogue-preview" id="products"><div class="section-heading reveal"><div>${eyebrow(t.home.rangeTag)}<h2>${e(t.home.rangeTitle)}</h2></div><p>${e(t.home.rangeDesc)}</p></div><div class="product-grid">${products.map(p=>productCard(p,t,lang)).join('')}</div><p class="range-photo-note">${e(t.imagery.disclaimer)}</p><div class="section-link">${button(t.common.allProducts,url(lang,'products/'),true)}</div></section>
 <section class="about-band"><div class="container about-band-inner">${brandArt(t)}<div class="about-band-copy reveal">${eyebrow(t.home.aboutTag)}<h2>${br(t.home.aboutTitle)}</h2><p>${e(t.home.aboutDesc)}</p><a class="text-link" href="${url(lang,'about/')}">${e(t.common.learn)}${icon('arrow','directional')}</a></div></div></section>
 <section class="container section process"><div class="section-heading reveal"><div>${eyebrow(t.home.processTag)}<h2>${e(t.home.processTitle)}</h2></div></div><div class="steps">${t.home.steps.map((x,i)=>`<div class="step reveal"><span class="step-number" dir="ltr">0${i+1}</span><h3>${e(x.title)}</h3><p>${e(x.text)}</p></div>`).join('')}</div></section>${cta(t,lang)}`;}
export function catalog(t,lang) {return `<section class="container section top-section">${heading(t.catalog.tag,t.catalog.title,t.catalog.desc)}<div class="catalog-tools"><div class="product-filters" role="group" aria-label="${e(t.catalog.filter)}">${['all','infusion','access','protection'].map((key,i)=>`<button type="button" data-filter="${key}" class="filter-button${i===0?' is-active':''}" aria-pressed="${i===0}">${e(t.catalog[key])}</button>`).join('')}</div><div class="search-field">${icon('search')}<label class="sr-only" for="product-search">${e(t.catalog.search)}</label><input type="search" id="product-search" placeholder="${e(t.catalog.searchPlaceholder)}" autocomplete="off"></div></div><div class="catalog-status" role="status" aria-live="polite"><span id="product-count">${new Intl.NumberFormat(lang).format(6)} ${e(t.catalog.count)}</span><span>${e(t.common.notCheckout)}</span></div><div class="product-grid filterable-grid">${products.map(p=>productCard(p,t,lang,true)).join('')}</div><div class="empty-state" hidden>${icon('search')}<h2>${e(t.catalog.empty)}</h2><p>${e(t.catalog.emptyDesc)}</p><button class="button" type="button" data-clear-filters>${e(t.catalog.reset)}</button></div><p class="catalog-note">${icon('info')}${e(t.catalog.note)} ${e(t.imagery.disclaimer)}</p></section>${cta(t,lang)}`;}
export function detail(t,lang,p) {
 const text=t.products[p.id];
 return `<section class="container section top-section product-detail"><a class="back-link" href="${url(lang,'products/')}">${icon('arrow','directional back-arrow')}${e(t.common.back)}</a><div class="detail-grid"><div class="detail-visual"><div class="detail-art art-${p.art}" data-depth="detail"><span class="detail-ref" dir="ltr">${p.ref}</span><img src="${assetUrl(`images/${p.art}.webp`)}" alt="${e(text.name)}" width="804" height="612" fetchpriority="high"><button class="photo-zoom-button" type="button" data-photo-zoom aria-label="${e(t.imagery.zoom)}">${icon('search')}<span>${e(t.imagery.zoom)}</span></button></div><p class="image-caption">${e(t.common.illustration)}</p><dialog class="photo-dialog" aria-labelledby="photo-dialog-title"><div class="photo-dialog-header"><h2 id="photo-dialog-title">${e(text.name)}</h2><button type="button" class="icon-button" data-photo-close aria-label="${e(t.imagery.close)}">${icon('close')}</button></div><img src="${assetUrl(`images/${p.art}.webp`)}" alt="${e(text.name)}" width="804" height="612" loading="lazy"><p>${e(t.common.illustration)}</p></dialog></div><div class="detail-copy">${eyebrow(t.catalog[p.category])}<h1>${e(text.name)}</h1><p class="detail-lead">${e(text.short)}</p><div class="detail-description"><h2>${e(t.detail.overview)}</h2><p>${e(text.description)}</p></div><dl class="product-meta"><div><dt>${e(t.common.reference)}</dt><dd dir="ltr">${p.ref}</dd></div><div><dt>${e(t.common.supply)}</dt><dd>${e(t.common.confirm)}</dd></div></dl>${button(t.common.enquire,url(lang,`contact/?product=${p.id}`))}<p class="small-note">${e(t.common.notCheckout)}</p></div></div><div class="detail-bottom"><div class="enquiry-points"><h2>${e(t.detail.discuss)}</h2><ul>${text.focus.map(f=>`<li>${icon('check')}<span>${e(f)}</span></li>`).join('')}</ul></div><aside class="spec-note">${icon('file')}<h2>${e(t.detail.specTitle)}</h2><p>${e(t.detail.specDesc)}</p></aside></div><p class="catalog-note">${icon('info')}${e(t.detail.notice)}</p></section><section class="help-band"><div class="container"><div><h2>${e(t.detail.helpTitle)}</h2><p>${e(t.detail.helpDesc)}</p></div><button class="button button-secondary" type="button" data-open-chat>${e(t.detail.helpCta)}${icon('chat')}</button></div></section><section class="container section"><div class="section-heading"><h2>${e(t.detail.related)}</h2><a class="text-link" href="${url(lang,'products/')}">${e(t.common.allProducts)}${icon('arrow','directional')}</a></div><div class="product-grid">${products.filter(x=>x.id!==p.id).sort((a,b)=>(a.category===p.category?-1:1)-(b.category===p.category?-1:1)).slice(0,3).map(x=>productCard(x,t,lang)).join('')}</div></section>`;
}
export function about(t,lang) {return `<section class="container section top-section about-intro">${heading(t.about.tag,t.about.title,t.about.intro)}${brandArt(t)}</section><section class="about-band"><div class="container about-mission"><h2>${br(t.about.missionTitle)}</h2><p>${e(t.about.missionText)}</p></div></section><section class="container section"><div class="value-grid">${t.about.values.map((v,i)=>`<div class="value-card reveal"><span class="value-number" aria-hidden="true" dir="ltr">0${i+1}</span><h2>${e(v.title)}</h2><p>${e(v.text)}</p></div>`).join('')}</div></section><section class="container language-section"><div>${eyebrow(t.common.footerLanguages)}<h2>${e(t.about.marketsTitle)}</h2><p>${e(t.about.marketsText)}</p></div><div class="language-tiles">${locales.map(l=>`<a href="${url(l.code,'about/')}" data-locale-link="${l.code}"><strong lang="${l.tag}" dir="auto">${e(l.name)}</strong><span dir="auto">${e(l.region)}</span>${icon('arrow','directional')}</a>`).join('')}</div></section>${cta(t,lang)}`;}
const inputField = (name,label,placeholder,options={}) => `<div class="field${options.full?' field-full':''}"><label for="${name}">${e(label)}${options.required?' <span aria-hidden="true">*</span>':` <span class="optional">${e(options.optional||'')}</span>`}</label><input id="${name}" name="${name}" type="${options.type||'text'}" placeholder="${e(placeholder)}" ${options.required?'required':''} ${options.autocomplete?`autocomplete="${options.autocomplete}"`:''} ${options.dir?`dir="${options.dir}"`:''} maxlength="${options.maxlength||160}" ${options.minlength?`minlength="${options.minlength}"`:''} aria-describedby="${name}-error"><span class="field-error" id="${name}-error"></span></div>`;
export function contact(t,lang,config) {
 const c=t.contact;
 const form=`<div class="contact-form-card"><h2>${e(c.formTitle)}</h2><p class="required-note">${e(t.common.required)}</p>${!config.contactEnabled?`<div class="preview-notice">${icon('info')}<span>${e(c.previewNote)}</span></div>`:''}<form id="contact-form" method="post" action="${e(config.contactEndpoint||'/api/contact')}" novalidate><div class="form-grid">${inputField('name',c.name,c.namePlaceholder,{required:true,autocomplete:'name',minlength:2,maxlength:100})}${inputField('email',c.email,c.emailPlaceholder,{required:true,type:'email',autocomplete:'email',dir:'ltr',maxlength:254})}${inputField('organisation',c.org,c.orgPlaceholder,{optional:t.common.optional,autocomplete:'organization',maxlength:160})}${inputField('phone',c.phone,'+91 …',{type:'tel',optional:t.common.optional,autocomplete:'tel',dir:'ltr',maxlength:40})}<div class="field"><label for="country">${e(c.country)} <span aria-hidden="true">*</span></label><select id="country" name="country" required aria-describedby="country-error"><option value="">${e(c.chooseCountry)}</option>${Object.entries(c.countries).map(([v,k])=>`<option value="${v}">${e(k)}</option>`).join('')}</select><span class="field-error" id="country-error"></span></div><div class="field"><label for="product">${e(c.product)}</label><select id="product" name="product"><option value="general">${e(t.common.general)}</option>${products.map(p=>`<option value="${p.id}">${e(t.products[p.id].name)}</option>`).join('')}</select></div>${inputField('quantity',c.quantity,c.quantityPlaceholder,{full:true,optional:t.common.optional,maxlength:100})}<div class="field field-full"><label for="message">${e(c.message)} <span aria-hidden="true">*</span></label><textarea id="message" name="message" rows="5" required minlength="10" maxlength="4000" placeholder="${e(c.messagePlaceholder)}" aria-describedby="message-error patient-note" dir="auto"></textarea><span class="field-error" id="message-error"></span><small id="patient-note">${e(c.patientNote)}</small></div><div class="honeypot" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" type="text" tabindex="-1" autocomplete="off"></div><div class="field-full consent-wrap"><label class="consent-label"><input type="checkbox" id="consent" name="consent" required aria-describedby="consent-error"><span>${e(c.consent)} <a href="${url(lang,'privacy/')}">${e(c.privacyLink)}</a></span></label><span class="field-error" id="consent-error"></span></div>${config.contactEnabled?`<div class="field-full"><div id="turnstile-widget" aria-label="${e(c.security)}"></div></div>`:''}<div class="field-full form-result" id="form-result" role="status" aria-live="polite" tabindex="-1" hidden></div><div class="field-full"><button class="button form-submit" type="submit" disabled><span>${e(c.send)}</span>${icon('arrow','directional')}</button></div></div></form></div>`;
 return `<section class="container section top-section contact-section"><div class="contact-intro">${heading(c.tag,c.title,c.desc)}<div class="contact-advice">${icon('chat')}<h2>${e(c.sideTitle)}</h2><p>${e(c.sideText)}</p><ul>${c.sideItems.map(x=>`<li>${icon('check')}${e(x)}</li>`).join('')}</ul></div></div>${form}</section>${faq(t)}`;
}
export function privacy(t,lang) {return `<section class="container section top-section prose-page">${heading(t.privacyPage.tag,t.privacyPage.title,t.privacyPage.intro)}<div class="prose">${t.privacyPage.sections.map(s=>`<section><h2>${e(s.title)}</h2><p>${e(s.text)}</p></section>`).join('')}</div>${button(t.nav.contact,url(lang,'contact/'))}</section>`;}
export function notFound(t,lang) {return `<section class="container section not-found"><span class="error-code" aria-hidden="true">404</span><h1>${e(t.errorPage.title)}</h1><p>${e(t.errorPage.text)}</p>${button(t.common.home,url(lang))}</section>`;}
