"""Browser checks for the portable preview. Requires Python Playwright + Chromium.
The site and build themselves have no Python or Playwright dependency.
"""
from pathlib import Path
import json, time, os, shutil
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
results=[]
def record(name,condition,detail=''):
    results.append({'name':name,'passed':bool(condition),'detail':detail})
    if not condition: print('FAIL',name,detail)
with sync_playwright() as p:
    executable=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium')
    browser=p.chromium.launch(headless=True, **({'executable_path':executable} if executable else {}))
    page=browser.new_page(viewport={'width':1440,'height':1000},device_scale_factor=1)
    page.set_default_timeout(7000)
    js_errors=[]
    page.on('pageerror',lambda error:js_errors.append(str(error)))
    page.route('https://fonts.googleapis.com/**',lambda route:route.abort())
    page.route('https://fonts.gstatic.com/**',lambda route:route.abort())
    page.emulate_media(reduced_motion='reduce')
    page.set_content((ROOT/'preview.html').read_text(),wait_until='domcontentloaded')
    go=lambda path:page.evaluate('(path)=>renderKS(path)',path)
    record('Homepage starts in English',page.locator('html').get_attribute('lang')=='en-IN')
    page.locator('.hero .button').click()
    record('Browse CTA opens catalogue',page.locator('#product-search').count()==1)
    page.locator('[data-filter="access"]').click()
    record('Category filter shows two access products',page.locator('[data-product]:visible').count()==2)
    page.locator('#product-search').fill('cannula')
    record('Search and category filters combine',page.locator('[data-product]:visible').count()==1)
    page.locator('#product-search').fill('no-such-product')
    record('Search has an empty state',page.locator('.empty-state').is_visible())
    page.locator('[data-clear-filters]').click()
    record('Clear filters restores six products',page.locator('[data-product]:visible').count()==6)
    page.locator('.product-card-link').first.click()
    record('Product details open',page.locator('h1').inner_text()=='IV infusion sets')
    page.locator('.detail-copy .button').click()
    record('Product is preselected in enquiry',page.locator('#product').input_value()=='iv-infusion-sets')
    page.locator('.form-submit').click()
    record('Empty form provides localized field errors',page.locator('[aria-invalid="true"]').count()==5)
    record('Invalid form focuses first field',page.evaluate('document.activeElement.id')=='name')
    for key,value in {'name':'Alex Buyer','email':'buyer@example.com','organisation':'Example Clinic','quantity':'1000 units','message':'Please share the product specifications and packaging options.'}.items():
        page.locator('#'+key).fill(value)
    page.locator('#country').select_option('IN')
    page.locator('#consent').check()
    page.locator('#language').select_option('fa')
    record('Persian sets RTL direction',page.locator('html').get_attribute('dir')=='rtl')
    record('Language change preserves form draft',page.locator('#name').input_value()=='Alex Buyer' and page.locator('#product').input_value()=='iv-infusion-sets' and page.locator('#consent').is_checked())
    page.locator('#language').select_option('en')
    page.locator('.form-submit').click()
    record('Preview never claims the enquiry was sent','has not been sent' in page.locator('#form-result').inner_text())
    record('Unsent enquiry remains intact',page.locator('#message').input_value().startswith('Please share'))
    record('Temporary language draft cleared after restoration',page.evaluate("(()=>{try{return sessionStorage.getItem('ks-language-draft:/')===null}catch{return true}})()"))
    page.locator('.chat-launcher').click()
    record('Support opens with input focus',page.locator('#chat-panel').is_visible() and page.evaluate('document.activeElement.id')=='chat-input')
    page.locator('#chat-input').fill('Bulk pricing')
    page.locator('.chat-form button').click()
    record('Support answers bulk enquiries','no online checkout' in page.locator('.chat-messages').inner_text())
    page.locator('#chat-input').fill('How to insert a cannula?')
    page.locator('.chat-form button').click()
    record('Support does not give clinical instructions','not medical advice' in page.locator('.chat-messages').inner_text())
    page.keyboard.press('Escape')
    record('Escape closes support and restores focus',not page.locator('#chat-panel').is_visible() and page.locator('.chat-launcher').evaluate('(el)=>el===document.activeElement'))
    for lang,query in [('ar','قفازات'),('fa','دستکش'),('tr','enjektör')]:
        go('/'+lang+'/products/')
        page.locator('#product-search').fill(query)
        record(f'Localized search works in {lang}',page.locator('[data-product]:visible').count()==1)
        page.locator('.chat-launcher').click()
        page.locator('[data-chat-topic="documents"]').click()
        expected=json.loads((ROOT/f'src/locales/{lang}.json').read_text())['chat']['answers']['documents']
        record(f'Localized chatbot replies in {lang}',expected in page.locator('.chat-messages').inner_text())
    go('/en/')
    page.set_viewport_size({'width':390,'height':844})
    page.locator('.menu-toggle').click()
    record('Mobile menu is accessible',page.locator('#mobile-menu').is_visible() and page.locator('.menu-toggle').get_attribute('aria-expanded')=='true')
    page.keyboard.press('Escape')
    record('Escape closes mobile menu',not page.locator('#mobile-menu').is_visible())
    # Photo assets are embedded, not a mockup screenshot or external hotlinks.
    go('/en/')
    page.set_viewport_size({'width':1440,'height':1000})
    record('Photo-style product assets replace all old SVG product images',page.locator('img[src$=".svg"]').count()==0 and page.locator('.product-card img[src^="data:image/webp"]').count()==6)
    go('/en/products/iv-infusion-sets/')
    page.locator('[data-photo-zoom]').click()
    record('Larger product image opens as a native modal',page.locator('.photo-dialog').evaluate('(d)=>d.open && d.matches(":modal")'))
    page.keyboard.press('Escape')
    record('Escape closes larger image and restores button focus',not page.locator('.photo-dialog').evaluate('(d)=>d.open') and page.locator('[data-photo-zoom]').evaluate('(b)=>b===document.activeElement'))
    go('/ar/products/iv-infusion-sets/')
    page.locator('[data-photo-zoom]').click()
    record('Photo modal works in Arabic RTL',page.locator('.photo-dialog').evaluate('(d)=>d.open && getComputedStyle(d).direction==="rtl"'))
    page.locator('[data-photo-close]').click()
    page.emulate_media(reduced_motion='no-preference')
    go('/en/')
    bounds=page.locator('[data-depth=hero]').bounding_box()
    page.mouse.move(bounds['x']+bounds['width']*.75,bounds['y']+bounds['height']*.3)
    page.wait_for_timeout(200)
    record('Desktop pointer produces actual perspective tilt',page.locator('[data-depth=hero]').evaluate('(e)=>e.style.getPropertyValue("--tilt-y")!=="0deg" && getComputedStyle(e).transform.startsWith("matrix3d")'))
    page.emulate_media(reduced_motion='reduce')
    page.wait_for_timeout(150)
    record('Switching to reduced motion resets and disables depth',page.locator('[data-depth=hero]').evaluate('(e)=>getComputedStyle(e).transform==="none" && e.style.getPropertyValue("--tilt-y")==="0deg"'))

    # Wide, tablet and narrow viewport reflow. Every page is rendered from production HTML.
    overflow=[]
    bars=[]; header_gaps=[]; language_missing=[]
    page_paths=['','products/','about/','contact/','privacy/','products/iv-infusion-sets/','products/blood-transfusion-sets/','products/measured-volume-sets/']
    for width in [320,390,768,1024,1440]:
        page.set_viewport_size({'width':width,'height':900})
        for lang in ['en','ar','fa','tr']:
            for path in page_paths:
                go('/'+lang+'/'+path)
                w=page.evaluate('({scroll:document.documentElement.scrollWidth,view:innerWidth})')
                if w['scroll']>w['view']+1:overflow.append({'width':width,'lang':lang,'path':path,'scroll':w['scroll']})
                case={'width':width,'lang':lang,'path':path}
                header=page.evaluate('''()=>({bar:document.querySelectorAll('.topbar').length,top:document.querySelector('.site-header').getBoundingClientRect().top})''')
                if header['bar']:bars.append(case)
                if abs(header['top'])>1:header_gaps.append(case)
                if not page.locator('[data-language-selector]').is_visible():language_missing.append(case)
    print('Layout matrix finished',flush=True)
    record('160 viewport/locale/page combinations have no horizontal overflow',len(overflow)==0,str(overflow))
    record('Announcement strip is absent across 160 viewport/locale/page combinations',not bars,str(bars))
    record('Navigation starts at the viewport top with no empty strip across 160 combinations',not header_gaps,str(header_gaps))
    record('Language selector remains visible across 160 combinations',not language_missing,str(language_missing))
    go('/en/')
    record('Reduced-motion preference is honoured',page.locator('[data-depth=hero]').evaluate("el=>getComputedStyle(el).transform")=='none')
    record('No client-side JavaScript errors',not js_errors,str(js_errors))
    # Core landmark and form association checks, not a claim of a full WCAG audit.
    record('One main landmark and one page heading',page.locator('main').count()==1 and page.locator('h1').count()==1)
    go('/en/contact/')
    missing=page.locator('#contact-form input:not([type=hidden]),#contact-form textarea,#contact-form select').evaluate_all("els=>els.filter(e=>!e.labels?.length).map(e=>e.id)")
    record('Every enquiry input has an associated label',not missing,str(missing))
    out=ROOT/'test-results/screenshots';out.mkdir(parents=True,exist_ok=True)
    for name,path,width,height in [('hero-desktop','/en/',1440,990),('home-desktop','/en/',1440,1000),('catalogue-desktop','/en/products/',1440,1000),('product-desktop','/en/products/iv-infusion-sets/',1440,1100),('contact-desktop','/en/contact/',1440,1100),('home-mobile','/en/',390,844),('home-arabic-mobile','/ar/',390,844),('persian-contact-mobile','/fa/contact/',390,844)]:
        page.set_viewport_size({'width':width,'height':height});go(path)
        page.screenshot(path=str(out/(name+'.png')),full_page=name not in ['hero-desktop','home-mobile'])
    browser.close()
(ROOT/'docs/browser-results.json').write_text(json.dumps(results,indent=2,ensure_ascii=False))
print(f"Browser checks: {sum(x['passed'] for x in results)}/{len(results)} passed")
if any(not x['passed'] for x in results):raise SystemExit(1)
